language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=ec387ff8c816220b90d137e1ee7d27f575d313e6dab871f2fb269b275544bb1a"
install:
  - "npm install -g npm@latest"
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
  - "npm explore grunt-mocha-cov -- npm install mocha@latest"
script:
  - "grunt ci"
node_js:
  - "4"
  - "5"
  - "6"
cache:
  directories:
    - 'node_modules'
